apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: 22i-2566-mern-app
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 30173